// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Cuid$BsCuid = require("../src/Cuid.bs.js");

var x = Cuid$BsCuid.make(/* () */0);

console.log(x);

exports.x = x;
/* x Not a pure module */
